spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
      show-sql: false
  datasource:
    dcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/miniautorizador?useTimezone=true&serverTimeZone=UTC

messages:
  saldoInsuficiente: Saldo insuficiente!
  senhaIncorreta: Senha incorreta!
  cartaoInvalido: Cartão inexistente!
  ok: OK
constants:
  senhaCorreta: SENHA_CORRETA
  senhaIncorreta: SENHA_INCORRETA
  saldoSuficiente: SALDO_SUFICIENTE
  saldoInsuficiente: SALDO_INSUFICIENTE