# usuário e senha de conexão com o banco de dados
#spring.datasource.username=root
#spring.datasource.password=
# url de conexão do banco de dados
#spring.datasource.url=jdbc:mysql://localhost:3306/miniautorizador
spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/miniautorizador