spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
      show-sql: false
  datasource:
    dcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/miniautorizador?useTimezone=true&serverTimeZone=UTC
  server:
    error:
      include-binding-errors=always
      include-message=always

    logging:
      level:
        org.springframework.web: DEBUG
        org.hibernate: ERROR

  messages:
    saldoInsuficiente: Saldo insuficiente!
    senhaIncorreta: Senha incorreta!
    cartaoInvalido: Cartão inexistente!
    ok: OK